### ISSUE TITLE
(not an issue)

### ISSUE THREAD

**Issue by Flinner** [leicaflorian/slides.com_downloader#1]
Thanks man really helpful project!

**Comment by leicaflorian** [comment]
Thank you. It was a nice project to create. 
If you need it, this extension is also available on the [chrome web store](https://chrome.google.com/webstore/detail/slidescom-downloader/bciknjamldhnbbckmgbchmkdcalngnco).

**Comment by Flinner** [comment]
I used the extension to download some slides before posting the issue :sweat_smile:
